{{- if .Values.node.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploy.node.serviceAccountName" . }}
  labels:
    {{- include "deploy.node.labels" . | nindent 4 }}
  {{- with .Values.node.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
