apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.react.fullname" . }}
  labels:
    {{- include "deploy.react.labels" . | nindent 4 }}
spec:
  type: {{ .Values.react.service.type }}
  ports:
    - port: {{ .Values.react.service.port }}
      targetPort: http
      {{if (and (eq .Values.react.service.type "NodePort") (not (empty .Values.react.service.nodePort)))}}
      nodePort: {{.Values.react.service.nodePort}}
      {{end}}
      protocol: TCP
      name: http
  selector:
    {{- include "deploy.react.selectorLabels" . | nindent 4 }}
