{{- if .Values.react.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploy.react.serviceAccountName" . }}
  labels:
    {{- include "deploy.react.labels" . | nindent 4 }}
  {{- with .Values.react.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
